name: Development Build
on:
  push:
    branches:
    - main
jobs:
  build-windows:
    name: Build
    uses: ./.github/workflows/build-windows.yml
  build-linux:
    name: Build
    uses: ./.github/workflows/build-windows-wine.yaml
