name: Development Build
on:
  push:
    branches:
    - main
jobs:
  build-windows:
    name: Build
    uses: ./.github/workflows/build-windows.yaml
  build-windows-wine:
    name: Build
    uses: ./.github/workflows/build-windows-wine.yaml
